### ISSUE TITLE
Compression / Optimization

### ISSUE THREAD

**Issue by 94726** [LeoTuet/ui-we-want-to-sleep#11]
![image](https://user-images.githubusercontent.com/58269084/152792455-aea05e1e-e142-4960-b5f5-f9e3d627976c.png)
Proposal:
- [ ] Brotli Compression
- [ ] webp instead of png (not sure about safari support: https://caniuse.com/webp)

**Comment by 94726** [comment]
There is a possibility to add brotli support to nginx without subscribing to nginx plus: https://github.com/google/ngx_brotli

**Comment by marcschwaiger** [comment]
@94726 This issue can be closed now as compression was added [here](https://github.com/LeoTuet/deployment-we-want-to-sleep/pull/7)

**Comment by 94726** [comment]
Closed as @marcschwaiger fixed it in https://github.com/LeoTuet/deployment-we-want-to-sleep/pull/7
