### ISSUE TITLE
Result Page for Ballot

### ISSUE THREAD

**Issue by LeoTuet** [LeoTuet/ui-we-want-to-sleep#12]
After each Ballot a Screen is needed which nicely displays the results of the ballot

**Comment by LeoTuet** [comment]
Any ideas on how we want to display the results ?

- Should it be an extra page or should it replace the voting section ? 
- If its an extra page should it always show the current status of the vote ?
- ...

**Comment by 94726** [comment]
I think we planned not to show the results. But I'd appreciate at least some information like the amount of people that already voted somewhere in the voting section. I suppose the results would then be made public in either a separate page or by replacing the voting section.

**Comment by LeoTuet** [comment]
![result](https://user-images.githubusercontent.com/79801759/169654017-a10163b9-d45b-4d74-9b5a-aca9e2d2cb60.jpeg)
Here is a design draft. One thing I like to add is the question above the results.
