### ISSUE TITLE
Missaligned Vote Section

### ISSUE THREAD

**Issue by 94726** [LeoTuet/ui-we-want-to-sleep#20]
The text above the captcha is to far leftbound
![image](https://user-images.githubusercontent.com/58269084/153251552-19cd3be5-1478-4136-bd07-ea74094cc6b2.png)

**Comment by LeoTuet** [comment]
![wwts](https://user-images.githubusercontent.com/79801759/153611452-b2ee15b6-c02a-4dbd-b32e-c08469f5d537.png)
