### ISSUE TITLE
Anzeigefehler Chrome Extension: Dark Reader

### ISSUE THREAD

**Issue by Bartflo20** [LeoTuet/ui-we-want-to-sleep#28]
Sers, 
die Obere Animation ist nicht kompatibel mit dem folgenden Chrome Addon: 
[Dark Reader Github](https://github.com/darkreader/darkreader) (Mehr als 4 Mio. User) 

**Erwartetes Verhalten:** Er lässt die Obere Animation unverändert. Nur den unteren Bereich mit dem Text verändert er.

**Falschen Verhalten:** Er färbt die Animation komplett ein. (siehe Bilder) Der untere Bereich wird korrekt verändert.

Ist natürlich nichts schwerwiegendes und wenn ihr das nicht als euer Problem seht, ist das auch verständlich.
Getestet auf Chrome (Win 10) und Safari (iOS)

Habe noch Bilder angehängt:
Chrome Extension Ein (Win10):
![Dark_Reader_ein](https://user-images.githubusercontent.com/80706061/153669986-2d946f8a-27e2-406b-80a5-43e24123f009.png)

Chrome Extension Aus (Win10):
![Dark_Reader_aus](https://user-images.githubusercontent.com/80706061/153670233-aab0f712-c7a1-4ca0-8e7b-014f7851157c.png)

Bei fragen stehe ich zur Verfügung.

**Comment by LeoTuet** [comment]
https://github.com/darkreader/darkreader/issues/4144

**Comment by LeoTuet** [comment]
In the future please also add a English translation when creating an Issue in German. Since Issues in German aren't common practice. Thank you!

**Comment by Bartflo20** [comment]
Ok, I understand. I thought I could only write it in German because some other people also [wrote issues/comments in German](https://github.com/LeoTuet/backend-we-want-to-sleep/issues/2).

**Comment by LeoTuet** [comment]
Yeah we will also change that in the Future 😄
