### ISSUE TITLE
Cookie banner for HCaptcha 

### ISSUE THREAD

**Issue by LeoTuet** [LeoTuet/ui-we-want-to-sleep#67]
HCaptcha uses cookies for that we need a Cookie banner.
When the cookie banner is displayed all input (tabbing, scrolling, clicking) should be blocked - until the cookies are accepted.

- [x] cookie banner
- [x] input is blocked
- [x] translation

@quintus-luis please provide a design.

**Comment by quintus-luis** [comment]
<img width="1157" alt="CleanShot 2022-03-24 at 08 27 22@2x" src="https://user-images.githubusercontent.com/46219079/159864372-365f30b8-8200-4e81-9ffd-4d8d3467f23b.png">
<img width="1165" alt="CleanShot 2022-03-24 at 08 27 38@2x" src="https://user-images.githubusercontent.com/46219079/159864404-de554b4e-b245-48dd-bb9a-b7851a5ae9f2.png">

Grid with 960px width
