### ISSUE TITLE
Admin Page

### ISSUE THREAD

**Issue by LeoTuet** [LeoTuet/ui-we-want-to-sleep#72]
For easier administration of our backend we should implement following features for admins:
- [ ] login page
- [ ] logout page
- [ ] section to generate token
- [ ] section to CRUD ballots

**Comment by LeoTuet** [comment]
@Aloso is this issue something you want TODO ?

**Comment by Aloso** [comment]
Yes, I can do that.

**Comment by Aloso** [comment]
Status update:

- I got the backend running locally
- I created a route for the admin area in the frontend
- The React component for the admin area is imported dynamically with `import()`, so it is only requested and downloaded when needed
- I made a prototype for the login page

Open questions:

- Does it need to be translated?

**Comment by LeoTuet** [comment]
We are the only ones who use it so we don't need a translation.

**Comment by Aloso** [comment]
Here are some screenshots of my first prototype:

<details>

<summary>Click to expand</summary>

![admin-area](https://user-images.githubusercontent.com/15658558/160297885-363811ce-7f5c-462e-967c-5d4f086eae2e.png)

![admin-area-2](https://user-images.githubusercontent.com/15658558/160297882-6a436021-5854-449f-b74e-e92dce2e9cf0.png)

![admin-area-3](https://user-images.githubusercontent.com/15658558/160297883-4073f40f-042b-423a-9e78-5ae4b9aecfcd.png)

</details>

Feedback is appreciated.

**Comment by 94726** [comment]
I'd appreciate a button to copy/download all the generated tokens.

**Comment by Aloso** [comment]
@94726 I implemented the download link.
